import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const gorst = localFont({
  src: "../fonts/gorst.ttf",
  display: "swap",
  variable: "--font-gorst",
  style: "normal",
});

export const metadata: Metadata = {
  title: "AIvy Post",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={gorst.className}>{children}</body>
    </html>
  );
}
